import SltAdminAlertWrapper from "@pango-studio/salt-admin-component-library/src/components/AdminAlertWrapper/AdminAlertWrapper.vue";
import SltAdminBadge from "@pango-studio/salt-admin-component-library/src/components/AdminBadge/AdminBadge.vue";
import SltAdminBreadcrumbs from "@pango-studio/salt-admin-component-library/src/components/AdminBreadcrumbs/AdminBreadcrumbs.vue";
import SltAdminButton from "@pango-studio/salt-admin-component-library/src/components/AdminButton/AdminButton.vue";
import SltAdminCardWrapper from "@pango-studio/salt-admin-component-library/src/components/AdminCardWrapper/AdminCardWrapper.vue";
import SltAdminCopyBadge from "@pango-studio/salt-admin-component-library/src/components/AdminCopyBadge/AdminCopyBadge.vue";
import SltAdminDropdownList from "@pango-studio/salt-admin-component-library/src/components/AdminDropdownList/AdminDropdownList.vue";
import SltAdminFormButtonGroup from "@pango-studio/salt-admin-component-library/src/components/AdminFormButtonGroup/AdminFormButtonGroup.vue";
import SltAdminFormDatePicker from "@pango-studio/salt-admin-component-library/src/components/AdminFormDatePicker/AdminFormDatePicker.vue";
import SltAdminFormHeading from "@pango-studio/salt-admin-component-library/src/components/AdminFormHeading/AdminFormHeading.vue";
import SltAdminFormInput from "@pango-studio/salt-admin-component-library/src/components/AdminFormInput/AdminFormInput.vue";
import SltAdminFormItemWrapper from "@pango-studio/salt-admin-component-library/src/components/AdminFormItemWrapper/AdminFormItemWrapper.vue";
import SltAdminFormSelect from "@pango-studio/salt-admin-component-library/src/components/AdminFormSelect/AdminFormSelect.vue";
import SltAdminFormTextArea from "@pango-studio/salt-admin-component-library/src/components/AdminFormTextArea/AdminFormTextArea.vue";
import SltAdminFormToggle from "@pango-studio/salt-admin-component-library/src/components/AdminFormToggle/AdminFormToggle.vue";
import SltAdminFormUpload from "@pango-studio/salt-admin-component-library/src/components/AdminFormUpload/AdminFormUpload.vue";
import SltAdminFormWrapper from "@pango-studio/salt-admin-component-library/src/components/AdminFormWrapper/AdminFormWrapper.vue";
import SltAdminLinkButton from "@pango-studio/salt-admin-component-library/src/components/AdminLinkButton/AdminLinkButton.vue";
import SltAdminRemoveBadge from "@pango-studio/salt-admin-component-library/src/components/AdminRemoveBadge/AdminRemoveBadge.vue";
import SltAdminProgressBar from "@pango-studio/salt-admin-component-library/src/components/AdminProgressBar/AdminProgressBar.vue";
import SltAdminStepItem from "@pango-studio/salt-admin-component-library/src/components/AdminStepItem/AdminStepItem.vue";
import SltAdminStepWrapper from "@pango-studio/salt-admin-component-library/src/components/AdminStepWrapper/AdminStepWrapper.vue";
import SltAdminTabButton from "@pango-studio/salt-admin-component-library/src/components/AdminTabButton/AdminTabButton.vue";
import SltAdminTabContentWrapper from "@pango-studio/salt-admin-component-library/src/components/AdminTabContentWrapper/AdminTabContentWrapper.vue";
import SltAdminTabGroup from "@pango-studio/salt-admin-component-library/src/components/AdminTabGroup/AdminTabGroup.vue";
import SltAdminTable from "@pango-studio/salt-admin-component-library/src/components/AdminTable/AdminTable.vue";
import SltAdminTableCell from "@pango-studio/salt-admin-component-library/src/components/AdminTableCell/AdminTableCell.vue";
import SltAdminTableHeader from "@pango-studio/salt-admin-component-library/src/components/AdminTableHeader/AdminTableHeader.vue";
import SltAdminTablePagination from "@pango-studio/salt-admin-component-library/src/components/AdminTablePagination/AdminTablePagination.vue";
import SltAdminTableRow from "@pango-studio/salt-admin-component-library/src/components/AdminTableRow/AdminTableRow.vue";
import SltAdminTableSearch from "@pango-studio/salt-admin-component-library/src/components/AdminTableSearch/AdminTableSearch.vue";
import SltIconArchive from "@pango-studio/salt-admin-component-library/src/components/IconArchive/IconArchive.vue";
import SltIconCopy from "@pango-studio/salt-admin-component-library/src/components/IconCopy/IconCopy.vue";
import SltIconRemove from "@pango-studio/salt-admin-component-library/src/components/IconRemove/IconRemove.vue";
import SltIconArrowDown from "@pango-studio/salt-admin-component-library/src/components/IconArrowDown/IconArrowDown.vue";
import SltIconArrowNext from "@pango-studio/salt-admin-component-library/src/components/IconArrowNext/IconArrowNext.vue";
import SltIconArrowPrev from "@pango-studio/salt-admin-component-library/src/components/IconArrowPrev/IconArrowPrev.vue";
import SltIconArrowUp from "@pango-studio/salt-admin-component-library/src/components/IconArrowUp/IconArrowUp.vue";
import SltIconAttachment from "@pango-studio/salt-admin-component-library/src/components/IconAttachment/IconAttachment.vue";
import SltIconClose from "@pango-studio/salt-admin-component-library/src/components/IconClose/IconClose.vue";
import SltIconCross from "@pango-studio/salt-admin-component-library/src/components/IconCross/IconCross.vue";
import SltIconDanger from "@pango-studio/salt-admin-component-library/src/components/IconDanger/IconDanger.vue";
import SltIconDashboard from "@pango-studio/salt-admin-component-library/src/components/IconDashboard/IconDashboard.vue";
import SltIconDislike from "@pango-studio/salt-admin-component-library/src/components/IconDislike/IconDislike.vue";
import SltIconDownload from "@pango-studio/salt-admin-component-library/src/components/IconDownload/IconDownload.vue";
import SltIconDownloadQueue from "@pango-studio/salt-admin-component-library/src/components/IconDownloadQueue/IconDownloadQueue.vue";
import SltIconDrag from "@pango-studio/salt-admin-component-library/src/components/IconDrag/IconDrag.vue";
import SltIconEdit from "@pango-studio/salt-admin-component-library/src/components/IconEdit/IconEdit.vue";
import SltIconExport from "@pango-studio/salt-admin-component-library/src/components/IconExport/IconExport.vue";
import SltIconEye from "@pango-studio/salt-admin-component-library/src/components/IconEye/IconEye.vue";
import SltIconFile from "@pango-studio/salt-admin-component-library/src/components/IconFile/IconFile.vue";
import SltIconFilter from "@pango-studio/salt-admin-component-library/src/components/IconFilter/IconFilter.vue";
import SltIconFolder from "@pango-studio/salt-admin-component-library/src/components/IconFolder/IconFolder.vue";
import SltIconImage from "@pango-studio/salt-admin-component-library/src/components/IconImage/IconImage.vue";
import SltIconImport from "@pango-studio/salt-admin-component-library/src/components/IconImport/IconImport.vue";
import SltIconIncorrect from "@pango-studio/salt-admin-component-library/src/components/IconIncorrect/IconIncorrect.vue";
import SltIconInfo from "@pango-studio/salt-admin-component-library/src/components/IconInfo/IconInfo.vue";
import SltIconLink from "@pango-studio/salt-admin-component-library/src/components/IconLink/IconLink.vue";
import SltIconList from "@pango-studio/salt-admin-component-library/src/components/IconList/IconList.vue";
import SltIconLoading from "@pango-studio/salt-admin-component-library/src/components/IconLoading/IconLoading.vue";
import SltIconMenu from "@pango-studio/salt-admin-component-library/src/components/IconMenu/IconMenu.vue";
import SltIconNotification from "@pango-studio/salt-admin-component-library/src/components/IconNotification/IconNotification.vue";
import SltIconPlus from "@pango-studio/salt-admin-component-library/src/components/IconPlus/IconPlus.vue";
import SltIconPlay from "@pango-studio/salt-admin-component-library/src/components/IconPlay/IconPlay.vue";
import SltIconRefresh from "@pango-studio/salt-admin-component-library/src/components/IconRefresh/IconRefresh.vue";
import SltIconSave from "@pango-studio/salt-admin-component-library/src/components/IconSave/IconSave.vue";
import SltIconSearch from "@pango-studio/salt-admin-component-library/src/components/IconSearch/IconSearch.vue";
import SltIconSortDown from "@pango-studio/salt-admin-component-library/src/components/IconSortDown/IconSortDown.vue";
import SltIconSortUp from "@pango-studio/salt-admin-component-library/src/components/IconSortUp/IconSortUp.vue";
import SltIconTag from "@pango-studio/salt-admin-component-library/src/components/IconTag/IconTag.vue";
import SltIconTick from "@pango-studio/salt-admin-component-library/src/components/IconTick/IconTick.vue";
import SltIconTile from "@pango-studio/salt-admin-component-library/src/components/IconTile/IconTile.vue";
import SltIconTrash from "@pango-studio/salt-admin-component-library/src/components/IconTrash/IconTrash.vue";
import SltIconUnarchive from "@pango-studio/salt-admin-component-library/src/components/IconUnarchive/IconUnarchive.vue";
import SltIconUser from "@pango-studio/salt-admin-component-library/src/components/IconUser/IconUser.vue";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    SltAdminAlertWrapper: typeof SltAdminAlertWrapper;
    SltAdminBadge: typeof SltAdminBadge;
    SltAdminBreadcrumbs: typeof SltAdminBreadcrumbs;
    SltAdminButton: typeof SltAdminButton;
    SltAdminCardWrapper: typeof SltAdminCardWrapper;
    SltAdminCopyBadge: typeof SltAdminCopyBadge;
    SltAdminDropdownlist: typeof SltAdminDropdownList;
    SltAdminFormButtonGroup: typeof SltAdminFormButtonGroup;
    SltAdminFormDatePicker: typeof SltAdminFormDatePicker;
    SltAdminFormHeading: typeof SltAdminFormHeading;
    SltAdminFormInput: typeof SltAdminFormInput;
    SltAdminFormItemWrapper: typeof SltAdminFormItemWrapper;
    SltAdminFormSelect: typeof SltAdminFormSelect;
    SltAdminFormTextArea: typeof SltAdminFormTextArea;
    SltAdminFormToggle: typeof SltAdminFormToggle;
    SltAdminFormUpload: typeof SltAdminFormUpload;
    SltAdminFormWrapper: typeof SltAdminFormWrapper;
    SltAdminLinkButton: typeof SltAdminLinkButton;
    SltAdminProgressBar: typeof SltAdminProgressBar;
    SltAdminRemoveBadge: typeof SltAdminRemoveBadge;
    SltAdminStepItem: typeof SltAdminStepItem;
    SltAdminStepWrapper: typeof SltAdminStepWrapper;
    SltAdminTabButton: typeof SltAdminTabButton;
    SltAdminTabContentWrapper: typeof SltAdminTabContentWrapper;
    SltAdminTableHeader: typeof SltAdminTableHeader;
    SltAdminTabGroup: typeof SltAdminTabGroup;
    SltAdminTable: typeof SltAdminTable;
    SltAdminTableCell: typeof SltAdminTableCell;
    SltAdminTablePagination: typeof SltAdminTablePagination;
    SltAdminTableRow: typeof SltAdminTableRow;
    SltAdminTableSearch: typeof SltAdminTableSearch;
    SltIconArchive: typeof SltIconArchive;
    SltIconCopy: typeof SltIconCopy;
    SltIconRemove: typeof SltIconRemove;
    SltIconArrowDown: typeof SltIconArrowDown;
    SltIconArrowNext: typeof SltIconArrowNext;
    SltIconArrowPrev: typeof SltIconArrowPrev;
    SltIconArrowUp: typeof SltIconArrowUp;
    SltIconAttachment: typeof SltIconAttachment;
    SltIconClose: typeof SltIconClose;
    SltIconCross: typeof SltIconCross;
    SltIconDanger: typeof SltIconDanger;
    SltIconDashboard: typeof SltIconDashboard;
    SltIconDislike: typeof SltIconDislike;
    SltIconDownload: typeof SltIconDownload;
    SltIconDownloadQueue: typeof SltIconDownloadQueue;
    SltIconDrag: typeof SltIconDrag;
    SltIconEdit: typeof SltIconEdit;
    SltIconExport: typeof SltIconExport;
    SltIconEye: typeof SltIconEye;
    SltIconFile: typeof SltIconFile;
    SltIconFilter: typeof SltIconFilter;
    SltIconFolder: typeof SltIconFolder;
    SltIconImage: typeof SltIconImage;
    SltIconImport: typeof SltIconImport;
    SltIconIncorrect: typeof SltIconIncorrect;
    SltIconInfo: typeof SltIconInfo;
    SltIconLink: typeof SltIconLink;
    SltIconList: typeof SltIconList;
    SltIconLoading: typeof SltIconLoading;
    SltIconMenu: typeof SltIconMenu;
    SltIconNotification: typeof SltIconNotification;
    SltIconPlus: typeof SltIconPlus;
    SltIconPlay: typeof SltIconPlay;
    SltIconRefresh: typeof SltIconRefresh;
    SltIconSave: typeof SltIconSave;
    SltIconSearch: typeof SltIconSearch;
    SltIconSortDown: typeof SltIconSortDown;
    SltIconSortUp: typeof SltIconSortUp;
    SltIconTag: typeof SltIconTag;
    SltIconTick: typeof SltIconTick;
    SltIconTile: typeof SltIconTile;
    SltIconTrash: typeof SltIconTrash;
    SltIconUnarchive: typeof SltIconUnarchive;
    SltIconUser: typeof SltIconUser;
  }
}
